// 'use client'
import type { Metadata } from "next";
// import { useEffect } from "react";
import jQuery from "jquery";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Head from "next/head";

import "./globals.css";
import "./assets/css/bootstrap.min.css";
import "./assets/css/style.css";
import "./assets/css/menu.css";
import "./assets/css/dashbord_navitaion.css";
import "./assets/css/magnific-popup.css";
import "./assets/css/bootstrap-select.min.css";
import "./assets/css/ace-responsive-menu.css";
import "./assets/css/ud-custom-spacing.css";
import "./assets/css/responsive.css";
import "./assets/css/flaticon.css";
import "./assets/css/animate.css";
import "./assets/css/fontawesome.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // useEffect(() => {
  //   window.$ = window.jQuery = jQuery;
  // }, []);

  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
        />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Preloader */}
        <div className="preloader" id="preloader"></div>

        {children}

        {/* External Scripts */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
          strategy="lazyOnload"
        />
        {/* <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
          strategy="lazyOnload"
        /> */}
        <Script
          src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"
          strategy="lazyOnload"
        />

        {/* Local Scripts */}
        {/* <Script src="/js/jquery-migrate-3.0.0.min.js" strategy="lazyOnload" /> */}
        <Script src="/js/popper.min.js" strategy="lazyOnload" />
        {/* <Script src="/js/bootstrap.min.js" strategy="lazyOnload" /> */}
        {/* <Script src="/js/bootstrap-select.min.js" strategy="lazyOnload" /> */}
        <Script src="/js/jquery.mmenu.all.js" strategy="lazyOnload" />
        {/* <Script src="/js/ace-responsive-menu.js" strategy="lazyOnload" /> */}
        {/* <Script src="/js/jquery-scrolltofixed-min.js" strategy="lazyOnload" /> */}
        {/* <Script src="/js/wow.min.js" strategy="lazyOnload" /> */}
        {/* <Script src="/js/owl.js" strategy="lazyOnload" /> */}
        {/* <Script src="/js/scrollbalance.js" strategy="lazyOnload" /> */}
        <Script src="/js/script.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
