
'use client';
// import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import "./css/fontawesome.css";
import { Provider } from "react-redux";
import { persistor, store } from "@/states/store";
import { PersistGate } from "redux-persist/es/integration/react";
import Preloader from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} antialiased`}
      >
        {/* <Preloader/> */}
         <Provider store={store}>
         <PersistGate loading={null} persistor={persistor}>
        {children}
      </PersistGate>
         </Provider>
  
      </body>
    </html>
  );
}
